/** @format */

import HomeLayout from '@layouts/HomeLayout'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Contapp Digital</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<HomeLayout />
		</div>
	)
}

export default Home
